services:
  flask-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app:ro
    command:
      - gunicorn
      - --bind
      - 0.0.0.0:5000
      - --workers
      - "1"
      - --reload
      - --reload-engine
      - poll
      - app.main:app
