const DATOS_CLIENTES = [
  {
    ID: 5524,
    Year_Birth: 1957,
    Education: 'Graduation',
    Marital_Status: 'Single',
    Income: 58138,
    Kidhome: 0,
    Teenhome: 0,
    Dt_Customer: '2012-09-04',
    Recency: 58,
    MntWines: 635,
    MntFruits: 88,
    MntMeatProducts: 546,
    MntFishProducts: 172,
    MntSweetProducts: 88,
    MntGoldProds: 88,
    NumDealsPurchases: 3,
    NumWebPurchases: 8,
    NumCatalogPurchases: 10,
    NumStorePurchases: 4,
    NumWebVisitsMonth: 7,
    AcceptedCmp1: 0,
    AcceptedCmp2: 0,
    AcceptedCmp3: 0,
    AcceptedCmp4: 0,
    AcceptedCmp5: 0,
    Complain: 0,
  },
  {
    ID: 2174,
    Year_Birth: 1954,
    Education: 'Graduation',
    Marital_Status: 'Single',
    Income: 46344,
    Kidhome: 1,
    Teenhome: 1,
    Dt_Customer: '2014-03-08',
    Recency: 38,
    MntWines: 11,
    MntFruits: 1,
    MntMeatProducts: 6,
    MntFishProducts: 2,
    MntSweetProducts: 1,
    MntGoldProds: 6,
    NumDealsPurchases: 2,
    NumWebPurchases: 1,
    NumCatalogPurchases: 1,
    NumStorePurchases: 2,
    NumWebVisitsMonth: 5,
    AcceptedCmp1: 0,
    AcceptedCmp2: 0,
    AcceptedCmp3: 0,
    AcceptedCmp4: 0,
    AcceptedCmp5: 0,
    Complain: 0,
  },
  {
    ID: 11191,
    Year_Birth: 1986,
    Education: 'Graduation',
    Marital_Status: 'Divorced',
    Income: 41411,
    Kidhome: 0,
    Teenhome: 0,
    Dt_Customer: '2013-12-07',
    Recency: 11,
    MntWines: 37,
    MntFruits: 32,
    MntMeatProducts: 38,
    MntFishProducts: 11,
    MntSweetProducts: 3,
    MntGoldProds: 18,
    NumDealsPurchases: 1,
    NumWebPurchases: 2,
    NumCatalogPurchases: 1,
    NumStorePurchases: 4,
    NumWebVisitsMonth: 6,
    AcceptedCmp1: 0,
    AcceptedCmp2: 0,
    AcceptedCmp3: 0,
    AcceptedCmp4: 0,
    AcceptedCmp5: 0,
    Complain: 0,
  },
  {
    ID: 2130,
    Year_Birth: 1982,
    Education: 'Graduation',
    Marital_Status: 'Together',
    Income: 45203,
    Kidhome: 2,
    Teenhome: 0,
    Dt_Customer: '2014-03-23',
    Recency: 4,
    MntWines: 35,
    MntFruits: 3,
    MntMeatProducts: 67,
    MntFishProducts: 10,
    MntSweetProducts: 8,
    MntGoldProds: 24,
    NumDealsPurchases: 1,
    NumWebPurchases: 3,
    NumCatalogPurchases: 1,
    NumStorePurchases: 3,
    NumWebVisitsMonth: 6,
    AcceptedCmp1: 0,
    AcceptedCmp2: 0,
    AcceptedCmp3: 0,
    AcceptedCmp4: 0,
    AcceptedCmp5: 0,
    Complain: 0,
  },
];

export async function obtener_clientes() {
  return DATOS_CLIENTES;
}

export async function obtener_cliente_por_id(id) {
  const num = Number(id);
  return DATOS_CLIENTES.find((c) => c.ID === num || c.id === num) || null;
}
